services:
  app:
    build: .
    environment:
      - FLASK_ENV=development
    ports: '- "5000:6000"'
    restart: unless-stopped
    volumes:
      - .:/app
      - ./uploads:/app/uploads
version: '3.8'
volumes:
  postgres_data: null
