# 示例配置文件
database:
  host: localhost
  port: 5432
  name: myapp
  user: admin
  password: secret123

server:
  host: 0.0.0.0
  port: 8080
  debug: true
  workers: 4

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/app.log
  max_size: 10MB
  backup_count: 5

features:
  cache_enabled: true
  rate_limit: 100
  timeout: 30
  retry_attempts: 3

email:
  smtp_server: smtp.gmail.com
  smtp_port: 587
  username: user@example.com
  password: app_password
  use_tls: true 